
a=int(input())
print('Tabuada do',a)
print('1 x',a,'=',1*a)
print('2 x',a,'=',2*a)
print('3 x',a,'=',3*a)
print('4 x',a,'=',4*a)
print('5 x',a,'=',5*a)
print('6 x',a,'=',6*a)
print('7 x',a,'=',7*a)
print('8 x',a,'=',8*a)
print('9 x',a,'=',9*a)
print('10 x',a,'=',10*a)
print('11 x',a,'=',11*a)
